server {
    listen 443 ssl;
    listen 2053 ssl;
    listen 2083 ssl;
    listen 2087 ssl;
    listen 2096 ssl;
    listen 8443 ssl;
    http2 on;
    server_name ssl-signer.js.gripe;

    ssl_certificate     /etc/openresty/ssl/js.gripe.fullchain.pem;
    ssl_certificate_key /etc/openresty/ssl/js.gripe.key.pem;

    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    charset utf-8;
    server_tokens off;

    include /usr/local/openresty/nginx/conf/cloudflare-only.inc;
    include /usr/local/openresty/nginx/conf/error_pages_server.inc;
    include /usr/local/openresty/nginx/conf/sensitive-deny.inc;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_pass http://127.0.0.1:19444;
    }
}

server {
    listen 80;
    server_name ssl-signer.js.gripe;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
